deislabs/hippo

.editorconfig
Hippo/ApiControllers/.editorconfig
Hippo/Controllers/AccountController.cs
Hippo/Controllers/AdminController.cs
Hippo/Controllers/AppController.cs
Hippo/Controllers/RevisionController.cs
Hippo/Controllers/StyleguideController.cs

Turns on enforcement of HttpVerb and Antiforgery attributes for any operation not under APiControllers folder.

Enforce Anitforgery and HttpVerb Attributes

---

.gitignore

these files are generated with .NET 6

remove .db-shm and .db-wal

---

Hippo/package-lock.json

switch to package-lock version 2

---

src/Hippo/Api/ApplicationController.cs
src/Hippo/Api/ChannelController.cs
src/Hippo/Controllers/AccountController.cs
src/Hippo/Controllers/AppController.cs
src/Hippo/Controllers/ApplicationControllerCore.cs
src/Hippo/Controllers/BaseController.cs
src/Hippo/Controllers/RevisionController.cs
src/Hippo/Messages/CreateApplicationRequest.cs
src/Hippo/OperationData/ICreateApplicationParameters.cs
src/Hippo/ViewModels/AppNewForm.cs

simplify naming: ApiControllers -> Api, ControllerCore -> Controllers

---

Hippo.sln
tests/Hippo.FunctionalTests/Controllers/AccountController.cs
tests/Hippo.FunctionalTests/Fakes/FakeCurrentUser.cs
tests/Hippo.FunctionalTests/Fakes/FakeSignInManager.cs
tests/Hippo.FunctionalTests/Fakes/FakeUserManager.cs
tests/Hippo.FunctionalTests/Fakes/NullLogger.cs
tests/Hippo.FunctionalTests/Hippo.FunctionalTests.csproj

re-introduces Hippo's functional tests in a separate package.

(re)introduce Hippo.FunctionalTests

---

tests/Hippo.FunctionalTests/Fakes/NullLogger.cs

fix spacing

---

.gitignore

fix gitgnore path for hippo.db*

---

src/Hippo/Program.cs
src/Hippo/Proxies/appsettings.Development.json
src/Hippo/WagiDotnet/appsettings.json

fixes issues running Hippo on MacOS: https://developer.apple.com/forums/thread/682332

change default listening ports to 5308/5309

---

src/Application/Channels/Commands/CreateChannelCommandValidator.cs
src/Application/Channels/Commands/UpdateChannelCommandValidator.cs
tests/Hippo.FunctionalTests/Application/Channels/Commands/CreateChannelTests.cs

closes #136
closes #145
closes #292

require unique domain name

---

tests/Hippo.FunctionalTests/Application/Accounts/Commands/CreateAccountTests.cs
tests/Hippo.FunctionalTests/Application/Channels/Commands/CreateChannelTests.cs
tests/Hippo.FunctionalTests/Application/Revisions/Commands/CreateRevisionTests.cs
tests/Hippo.FunctionalTests/TestBase.cs

due to conflicting duplicate data in the class

fix failing functional tests

---

src/Web/Controllers/AppController.cs
src/Web/Controllers/ChannelController.cs
src/Web/Controllers/EnvironmentVariableController.cs

require user to sign in

---

.devcontainer/devcontainer.json
src/Application/Channels/EventHandlers/ActiveRevisionChangedEventHandler.cs
src/Application/Channels/EventHandlers/ChannelCreatedEventHandler.cs
src/Application/Channels/EventHandlers/ChannelDeletedEventHandler.cs
src/Application/Common/Interfaces/IJobScheduler.cs
src/Application/Common/Interfaces/IReverseProxy.cs
src/Infrastructure/JobSchedulers/LocalJobScheduler.cs
src/Infrastructure/ReverseProxies/YarpReverseProxy.cs
src/Web/appsettings.Development.json

start serving requests for the channel via IReverseProxy

---

src/Application/Channels/Commands/CreateChannelCommand.cs
src/Application/Channels/Commands/CreateChannelCommandValidator.cs
src/Application/Common/Config/HippoConfig.cs
src/Infrastructure/DependencyInjection.cs
src/Web/Views/Channel/New.cshtml
src/Web/appsettings.json
src/Web/assets/js/app.js
src/Web/assets/js/dist/app.dev.js
tests/Hippo.FunctionalTests/Application/Channels/Commands/CreateChannelTests.cs
tests/Hippo.FunctionalTests/Application/Channels/Commands/UpdateChannelTests.cs
tests/Hippo.FunctionalTests/TestBase.cs

apply default domain to channel if none provided

---

src/Web/Controllers/AppController.cs
src/Web/Controllers/ChannelController.cs
src/Web/Controllers/EnvironmentVariableController.cs

handle ValidationExceptions

---

src/Application/Application.csproj
src/Core/Core.csproj
src/Infrastructure/Infrastructure.csproj
src/Web/Web.csproj

https://docs.microsoft.com/en-ca/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli

add nuget package information

---

src/Core/Entities/Channel.cs
src/Web/appsettings.Development.json

fix: emit ActiveRevisionChangedEvent when ActiveRevision is set

---

src/Application/Channels/Commands/CreateChannelCommand.cs
src/Application/Channels/Commands/CreateChannelCommandValidator.cs
src/Application/Channels/Commands/UpdateChannelCommand.cs
src/Application/Channels/Commands/UpdateChannelCommandValidator.cs
tests/Hippo.FunctionalTests/Application/Channels/Commands/CreateChannelTests.cs

set default range rule if none set

---

src/Web/Api/AccountController.cs
src/Web/Api/AppController.cs
src/Web/Api/CertificateController.cs
src/Web/Api/ChannelController.cs
src/Web/Api/EnvironmentVariableController.cs
src/Web/Api/RevisionController.cs

fix(api): fix API routes for Delete, Export, and Index

---

src/Infrastructure/DependencyInjection.cs
src/Infrastructure/ReverseProxies/YarpReverseProxy.cs
src/Web/appsettings.Development.json
src/Web/appsettings.json

remove ReverseProxy::Enabled config

---

src/Core/Entities/Channel.cs
tests/Core.UnitTests/Events/EventTests.cs

fix: emit CertificateBindEvent when Certificate changes

---

src/Web/Api/ApiControllerBase.cs
src/Web/Filters/ApiExceptionFilterAttribute.cs

introduce ApiExceptionFilter

---

src/Application/Apps/Commands/DeleteAppCommand.cs
src/Application/Apps/Commands/PurgeAppsCommand.cs
src/Application/Certificates/Commands/DeleteCertificateCommand.cs
src/Application/Certificates/Commands/PurgeCertificatesCommand.cs
src/Application/Channels/Commands/DeleteChannelCommand.cs
src/Application/Channels/Commands/PurgeChannelsCommand.cs
src/Application/Channels/EventHandlers/ChannelDeletedEventHandler.cs
src/Application/EnvironmentVariables/Commands/DeleteEnvironmentVariableCommand.cs
src/Application/EnvironmentVariables/Commands/PurgeEnvironmentVariablesCommand.cs
src/Application/Revisions/Commands/DeleteRevisionCommand.cs
src/Application/Revisions/Commands/PurgeRevisionsCommand.cs
tests/Core.UnitTests/Events/EventTests.cs

emit Deleted events

---

tests/Hippo.FunctionalTests/TestBase.cs

implement NullJobScheduler

---

src/Web/package-lock.json

npm update

---

src/Web/ClientApp/src/js/app.js

fixes issues with the "create channel" form.

fix jQuery import

---

src/Application/Channels/Queries/ChannelDto.cs

fix: display Certificate in ChannelDTO

---

src/Infrastructure/Data/SqliteDbContext.cs

fix(Infrastructure): use proper database driver for sqlite

---

src/Web/Web.csproj

not required as they are part of the package

remove broken includes

---

src/Application/Application.csproj
src/Core/Core.csproj
src/Infrastructure/Infrastructure.csproj
src/Web/Web.csproj

include LICENSE file in nupkg

---

src/Web/Views/Shared/_Footer.cshtml
src/Web/Views/Styleguide/Index.cshtml
src/Web/Web.csproj

I just walk through the source code and find some redundant codes and typos so I fixed them.

Fixed redundant codes and typo in views

---

src/Application/Channels/Commands/CreateChannelCommand.cs
src/Application/Common/Config/HippoConfig.cs
src/Web/appsettings.Development.json
src/Web/appsettings.json

fixes an issue where setting `Hippo:PlatformDomain` doesn't actually do anything.
TODO:

fix PlatformDomain not being set

---

src/Infrastructure/JobSchedulers/NomadJobScheduler.cs

allow to change nomad's datacenters

---

src/Infrastructure/JobSchedulers/NomadJobScheduler.cs

switch to an exec driver

---

src/Infrastructure/JobSchedulers/NomadJobScheduler.cs
src/Web/appsettings.json

tested manually... Should be working now

fix job definition

---

src/Infrastructure/JobSchedulers/NomadJobScheduler.cs

fix missing closing bracket

---

src/Application/Apps/Commands/UpdateAppCommand.cs
src/Application/Channels/EventHandlers/ActiveRevisionChangedEventHandler.cs
src/Application/Common/Interfaces/IJobFactory.cs
src/Application/Jobs/Job.cs
src/Infrastructure/Jobs/LocalJob.cs
src/Infrastructure/Jobs/LocalJobFactory.cs
src/Infrastructure/Jobs/NomadJob.cs
src/Infrastructure/Jobs/NomadJobFactory.cs
tests/Hippo.FunctionalTests/TestBase.cs

introduce Reload API

---

src/Application/Apps/Commands/CreateAppCommandValidator.cs
src/Application/Apps/Commands/UpdateAppCommandValidator.cs
tests/Hippo.FunctionalTests/Application/Apps/Commands/CreateAppTests.cs

accept dots in the storage ID name

---

.devcontainer/Dockerfile

devcontainer dep update

---

src/Web/ClientApp/package-lock.json

run `dotnet build`

---

src/Application/Revisions/EventHandlers/RevisionCreatedEventHandler.cs

load envvars when loading channel

---

src/Infrastructure/Jobs/NomadJob.cs

redirect standard input

---

src/Infrastructure/Jobs/NomadJob.cs

enable letsencrypt support for nomad

---

.devcontainer/Dockerfile
.github/release-image/Dockerfile

fix release image

---

.devcontainer/Dockerfile
.github/release-image/Dockerfile
.github/workflows/build-devcontainer.yml
src/Infrastructure/Jobs/LocalJob.cs
src/Infrastructure/Jobs/NomadJob.cs

replace wagi with spin

---

src/Application/Apps/Commands/DeleteAppCommand.cs
src/Application/Apps/Commands/UpdateAppCommand.cs
src/Application/Apps/Queries/GetAppQuery.cs
src/Application/Certificates/Commands/DeleteCertificateCommand.cs
src/Application/Certificates/Commands/UpdateCertificateCommand.cs
src/Application/Certificates/Queries/GetCertificateQuery.cs
src/Application/Channels/Commands/CreateChannelCommand.cs
src/Application/Channels/Commands/DeleteChannelCommand.cs
src/Application/Channels/Commands/UpdateChannelCommand.cs
src/Application/Channels/Commands/UpdateChannelCommandValidator.cs
src/Application/Channels/EventHandlers/ActiveRevisionChangedEventHandler.cs
src/Application/Channels/Queries/GetChannelQuery.cs
src/Application/Common/Behaviours/AuthorizationBehaviour.cs
src/Application/Common/Behaviours/DomainEventPublishingBehaviour.cs
src/Application/EnvironmentVariables/Commands/DeleteEnvironmentVariableCommand.cs
src/Application/EnvironmentVariables/Commands/UpdateEnvironmentVariableCommand.cs
src/Application/EnvironmentVariables/Queries/GetEnvironmentVariableQuery.cs
src/Application/Revisions/Commands/DeleteRevisionCommand.cs
src/Application/Rules/RevisionRangeRule.cs
src/Core/Common/ValueObject.cs
src/Infrastructure/Identity/IdentityService.cs
src/Infrastructure/Identity/SignInService.cs
src/Infrastructure/Jobs/LocalJob.cs
src/Infrastructure/Jobs/LocalJobFactory.cs
src/Infrastructure/Jobs/NomadJob.cs
src/Infrastructure/Jobs/NomadJobFactory.cs
tests/Application.UnitTests/Common/Mappings/MappingTests.cs

Introduced in C# 9: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#pattern-matching-enhancements

Simplified null validation

---

src/Application/Application.csproj
src/Core/Core.csproj
src/Infrastructure/Infrastructure.csproj
src/Web/Web.csproj

hippo 0.6.0

---

.github/release-image/Dockerfile

fix spin steps for release-image

---

src/Application/EnvironmentVariables/Commands/CreateEnvironmentVariableCommand.cs
src/Application/EnvironmentVariables/EventHandlers/EnvironmentVariableCreatedEventHandler.cs
src/Application/EnvironmentVariables/EventHandlers/EnvironmentVariableDeletedEventHandler.cs
src/Application/Revisions/Commands/CreateRevisionCommand.cs
src/Application/Revisions/Commands/RegisterRevisionCommand.cs
tests/Hippo.FunctionalTests/Application/EnvironmentVariables/Commands/CreateEnvironmentVariableTests.cs

Restart job when adding environment variable

---

src/Application/Revisions/EventHandlers/RevisionDeletedEventHandler.cs

While this code path is not actively used, the behaviour of the
RevisionDeletedEventHandler should match the behaviour of
RevisionCreatedEventHandler.

Fix: fire ModifiedEvent<Channel>

---

src/Application/Apps/Commands/UpdateAppCommand.cs
src/Application/Certificates/Queries/CertificateDto.cs
src/Application/Certificates/Queries/CertificateRecord.cs
src/Application/Channels/EventHandlers/ActiveRevisionChangedEventHandler.cs
src/Application/Jobs/Job.cs
src/Infrastructure/Data/Migrations/Postgresql/20220203223719_Initial.cs
src/Infrastructure/Data/Migrations/Sqlite/20211214002400_Initial.cs
src/Infrastructure/Data/Migrations/Sqlite/20220118175137_AddCertificates.cs
src/Infrastructure/Jobs/LocalJob.cs

Remove unnecessary usings

---

.devcontainer/devcontainer.json

add markdownlint as devcontainer extension

---

.devcontainer/Dockerfile
.github/release-image/Dockerfile
.github/workflows/build-devcontainer.yml

hippo-cli 0.11.0

---

src/Web/Api/AppController.cs
src/Web/Api/CertificateController.cs
src/Web/Api/ChannelController.cs
src/Web/Api/EnvironmentVariableController.cs

Implement "edit" API endpoints

---

src/Application/Accounts/Commands/CreateTokenCommand.cs
src/Application/Accounts/Commands/LoginAccountCommand.cs
src/Application/Common/Interfaces/IIdentityService.cs
src/Infrastructure/Identity/IdentityService.cs
src/Web/Filters/ApiExceptionFilterAttribute.cs
tests/Hippo.FunctionalTests/Application/Accounts/Commands/CreateTokenTests.cs

fix logging in returning 500 server error

---

src/Application/Accounts/Commands/CreateAccountCommandValidator.cs
src/Infrastructure/DependencyInjection.cs
tests/Hippo.FunctionalTests/Application/Accounts/Commands/CreateAccountTests.cs

remove ASP.NET Core Identity's password requirements

---

src/Web/Filters/ApiExceptionFilterAttribute.cs

handle JobFailedException

---

src/Web/ClientApp/src/app/components/channel/new/new.component.ts
src/Web/ClientApp/src/app/core/api/v1/.openapi-generator/FILES
src/Web/ClientApp/src/app/core/api/v1/api/app.service.ts
src/Web/ClientApp/src/app/core/api/v1/api/certificate.service.ts
src/Web/ClientApp/src/app/core/api/v1/api/channel.service.ts
src/Web/ClientApp/src/app/core/api/v1/api/environmentVariable.service.ts
src/Web/ClientApp/src/app/core/api/v1/model/models.ts
src/Web/ClientApp/src/app/core/api/v1/model/updateAppCommand.ts
src/Web/ClientApp/src/app/core/api/v1/model/updateCertificateCommand.ts
src/Web/ClientApp/src/app/core/api/v1/model/updateChannelCommand.ts
src/Web/ClientApp/src/app/core/api/v1/model/updateEnvironmentVariableCommand.ts

update UI's openapi client

---

src/Application/Accounts/Commands/CreateAccountCommand.cs
src/Application/Accounts/Commands/CreateAccountCommandValidator.cs
src/Web/ClientApp/src/app/components/account/register/register.component.ts
src/Web/ClientApp/src/app/core/api/v1/model/createAccountCommand.ts
tests/Hippo.FunctionalTests/Application/Accounts/Commands/CreateAccountTests.cs
tests/Hippo.FunctionalTests/Application/Accounts/Commands/CreateTokenTests.cs

This should be done on the client-side. Not required server-side.

remove PasswordConfirm from CreateAccountCommand

---

src/Web/ClientApp/src/app/components/application/list/list.component.html
src/Web/ClientApp/src/app/components/channel/list/list.component.html

https://bulma.io/documentation/columns/options/#multiline

set is-multiline

---

.devcontainer/Dockerfile
.github/release-image/Dockerfile
.github/workflows/build-devcontainer.yml

hippo-cli v0.12.0

---

src/Infrastructure/Jobs/NomadJob.cs

Also removes platform specific download of spin

fix(nomad): Fix the hcl syntax error

---

src/Application/Accounts/Commands/CreateAccountCommandValidator.cs
src/Web/ClientApp/src/app/components/account/register/register.component.html
src/Web/ClientApp/src/app/components/account/register/register.component.ts

We could add a task for creating a component for error handling and using it everywhere else as well. As this was used only here, I did not create a separate component.
I misnamed the branch name on the fork to 677, instead of 673.

Fix 673 / Present error on bad registration

---

src/Web/ClientApp/src/app/_helpers/constants.ts

fix formatting

---

src/Web/Web.csproj

include wwwroot in the published package

---

src/Web/appsettings.Development.json
src/Web/appsettings.json

fix indentation

---

src/Application/Apps/EventHandlers/CreateInitialChannel.cs
src/Application/Apps/Queries/GetAppQuery.cs
src/Infrastructure/Services/BindleService.cs
src/Infrastructure/Services/NomadService.cs
tests/Hippo.FunctionalTests/FakeBindleService.cs
tests/Hippo.FunctionalTests/TestBase.cs

Run `dotnet format`

---

src/Web/ClientApp/angular.json
src/Web/Web.csproj

fix `dotnet publish`

---

.vscode/launch.json
.vscode/tasks.json
src/Web/Properties/launchSettings.json

implement VSCode Tasks: build, run, watch, ng:watch

---

.github/workflows/publish-to-nuget.yaml

Publish to NuGet

---

src/Web/Program.cs

map /healthz endpoint

---

.github/workflows/publish-to-nuget.yaml

run `dotnet pack` not `dotnet build`

---

src/Infrastructure/HealthChecks/BindleHealthCheck.cs
src/Infrastructure/HealthChecks/NomadHealthCheck.cs
src/Infrastructure/Services/NomadService.cs
src/Web/Program.cs

implement bindle and nomad healthchecks

---

src/Infrastructure/Services/NomadService.cs

Remove unneeded square brackets

---

src/Web/ClientApp/package-lock.json
src/Web/Web.csproj

run `npm install` only on changes to package.json

---

src/Application/Apps/Queries/GetAppsQuery.cs
src/Infrastructure/Services/NomadJobService.cs
tests/Hippo.FunctionalTests/TestBase.cs

set tls to true

---

.github/workflows/publish-release.yml

missing steps

---

.github/workflows/publish-release.yml

add `runs-on` field

---

.github/workflows/publish-devcontainer.yml
.github/workflows/publish-docker.yml

Use docker/metadata-action instead

remove DEVCONTAINER_VERSION

---

.github/workflows/publish-release.yml

fix error 'Unexpected symbol: '"win-x64"''

---

.github/workflows/publish-release.yml

fix: depend on build_assets

---

src/Infrastructure/Infrastructure.csproj
src/Infrastructure/Services/BindleService.cs
src/Web/appsettings.Development.json
src/Web/appsettings.json

addresses some of the issues described in #819.

Deislabs.Bindle 0.2.0

---

src/Infrastructure/HealthChecks/BindleHealthCheck.cs

Missed this change in #831. Thanks to @michelleN for identifying this issue.

fix bindle healthcheck setting

---

.devcontainer/Dockerfile
.github/release-image/Dockerfile
src/Application/Application.csproj
src/Core/Core.csproj
src/Infrastructure/Infrastructure.csproj
src/Web/Web.csproj

bump to hippo 0.14

---

src/Infrastructure/Jobs/NomadJob.cs

Another issue falling out from #831. 🐑

read bindle URL from connection string

---

src/Application/EnvironmentVariables/Commands/UpdateChannelEnvironmentVariablesCommand.cs

check for null channel reference

---

.github/release-image/Dockerfile

drop generator-wasm

---

.devcontainer/Dockerfile

hippo-cli 0.12

---

src/Application/Apps/Commands/DeleteAppCommand.cs
src/Application/Apps/Commands/UpdateAppCommand.cs
src/Application/Apps/Queries/GetAppQuery.cs
src/Application/Apps/Queries/GetAppsQuery.cs
src/Application/Certificates/Commands/CreateCertificateCommand.cs
src/Application/Certificates/Commands/DeleteCertificateCommand.cs
src/Application/Certificates/Commands/UpdateCertificateCommand.cs
src/Application/Channels/Commands/CreateChannelCommand.cs
src/Application/Channels/Commands/DeleteChannelCommand.cs
src/Application/Channels/Commands/UpdateChannelCommand.cs
src/Application/Channels/EventHandlers/ChannelDeletedEventHandler.cs
src/Application/Channels/Queries/ChannelExtensions.cs
src/Application/Channels/Queries/GetChannelLogsQuery.cs
src/Application/Common/Interfaces/IJobService.cs
src/Application/EnvironmentVariables/Commands/CreateEnvironmentVariableCommand.cs
src/Application/EnvironmentVariables/Commands/DeleteEnvironmentVariableCommand.cs
src/Application/EnvironmentVariables/Commands/UpdateEnvironmentVariableCommand.cs
src/Application/EnvironmentVariables/Commands/UpdateEnvironmentVariableDto.cs
src/Application/Jobs/Job.cs
src/Application/Revisions/Commands/CreateRevisionCommand.cs
src/Application/Revisions/Commands/DeleteRevisionCommand.cs
src/Application/Revisions/Commands/RegisterRevisionCommand.cs
src/Infrastructure/DependencyInjection.cs
src/Infrastructure/Jobs/NomadJob.cs
src/Web/Api/ChannelController.cs
src/Web/Api/StorageController.cs

remove unused imports

---

.github/workflows/publish-docker.yml
.github/workflows/publish-nuget.yaml
.github/workflows/publish-release.yml
src/Application/Application.csproj
src/Core/Core.csproj
src/Infrastructure/Infrastructure.csproj
src/Web/Web.csproj

use minver

---

.github/workflows/publish-release.yml

ignore pre-releases when generating changelog

---

src/Application/Application.csproj
src/Core/Core.csproj
src/Infrastructure/Infrastructure.csproj
src/Web/Web.csproj

add minver tag prefix

---

.devcontainer/Dockerfile
.github/release-image/Dockerfile

hippo-cli 0.13.0

---

src/Web/ClientApp/package-lock.json
src/Web/ClientApp/package.json

angular 14.0.1

---

src/Web/appsettings.Development.json
src/Web/appsettings.json

increase log verbosity in production

---

src/Web/Filters/ApiExceptionFilterAttribute.cs

log unhandled exceptions

---

src/Application/EnvironmentVariables/Commands/UpdateChannelEnvironmentVariablesCommand.cs

UpdateChannelEnvironmentVariablesCommand

fix: fire CreatedEvent/DeletedEvent for

---

src/Web/ClientApp/src/index.html

load custom js if present

---

src/Web/ClientApp/src/app/components/navbar/navbar.component.html
src/Web/ClientApp/src/app/components/navbar/navbar.component.ts

expandable menu

---

src/Web/ClientApp/src/app/app.component.html

this is already covered with the `is-fluid` class.

remove mx-4

---

src/Application/Channels/Commands/PatchChannelCommand.cs
src/Core/Models/Filter.cs
src/Core/Models/Page.cs
src/Core/Serialization/FieldConverter.cs

fix nullability warnings

---

.github/dependabot.yml
src/Core/Core.csproj

add Core to dependabot

---

src/Application/Revisions/Queries/RevisionItem.cs
tests/Application.UnitTests/Revisions/Queries/RevisionItemTests.cs

sortable revision items

---

.github/dependabot.yml
Hippo.sln
src/Application/Common/Interfaces/BindleService/RevisionSpinToml.cs
src/Application/Revisions/Commands/UpdateRevisionDetailsCommand.cs
src/Infrastructure/Services/BindleService.cs
tests/Core.UnitTests/Common/AuditableEntityTests.cs
tests/Core.UnitTests/Enums/ChannelRevisionSelectionStrategyTests.cs
tests/Core.UnitTests/Enums/RegistrationModeTests.cs
tests/Core.UnitTests/Events/EventTests.cs
tests/Core.UnitTests/Exceptions/ExceptionTests.cs
tests/Infrastructure.UnitTests/Infrastructure.UnitTests.csproj
tests/Infrastructure.UnitTests/Services/BindleServiceTests.cs

Add support for SIP 002: Application Configuration

---

.devcontainer/Dockerfile
.github/release-image/Dockerfile

bump to hippo-cli v0.14.1

---

src/Core/Enums/ChannelRevisionSelectionStrategy.cs
src/Core/Enums/RegistrationMode.cs

Closes: #1065 
Signed-off-by: gogeterobert <gogeterobert@yahoo.com>

Added Data Annotations for correctly parsing enums to strings

---

src/Infrastructure/Common/MediatorExtensions.cs
src/Infrastructure/Data/ApplicationDbContext.cs

emit Deleted Domain events

---

src/Application/Channels/Commands/CreateChannelCommand.cs
src/Application/Revisions/EventHandlers/RevisionCreatedEventHandler.cs
src/Infrastructure/Data/Interceptors/AuditableEntitySaveChangesInterceptor.cs
src/Infrastructure/Services/DateTimeService.cs
src/Infrastructure/Services/TokenService.cs

use DateTime.UtcNow

---

src/Application/Channels/Commands/CreateChannelCommand.cs
tests/Hippo.FunctionalTests/Application/Channels/Commands/CreateChannelTests.cs
tests/Hippo.FunctionalTests/TestBase.cs

Also removes channel name from domain if only 1 channel

use dashes between channel/app name
