deislabs/hippo

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/release-image/Dockerfile
.github/workflows/build-devcontainer.yml
.github/workflows/manual-build-container.yml
.github/workflows/release.yml

Updates container definitions to use the latest versions of dependencies.
Adds a manual pipeline to enable the updating of runtime container image when dependencies have new versions but there is no new version of hippo. (As is the case with this PR where we have already released v0.1.0 but we need to update the container image associated with that version with new versions of bindle, wagi etc.)

update container definitions

---

Hippo/Views/Shared/_Footer.cshtml

Docs footer link doesnt take you to the official docs
Closes #277 
Signed-off-by: Nitish Malhotra <nitish.malhotra@gmail.com>

Hippo footer docs link broken

---

src/Hippo/Proxies/YarpReverseProxy.cs
src/Hippo/Schedulers/InternalScheduler.cs
src/Hippo/Schedulers/WagiDotnetJobScheduler.cs
src/Hippo/Schedulers/WagiLocalJobScheduler.cs

If the configured job scheduler is an instance of InternalScheduler, it will subscribe to those events.
This change removes the hard dependency on reverse proxies for certain schedulers.
With this change, we should consider collapsing InternalScheduler and ExternalScheduler as one Scheduler class. Then in Startup.cs, when the reverse proxy is enabled, we subscribe it to the scheduler's event handlers. That should help solve #242.

subscribe to channel start/stop events

---

.github/dependabot.yml

Core is ignored because it (intentionally) does not contain any dependencies.

update dependabot watch locations

---

src/Application/Apps/Commands/UpdateAppCommand.cs

If the user changes the bindle storage id, ALL channels will stop working until the user registers new revisions that satisfy the channels' rules.

stop all channels when storage ID has been updated

---

src/Infrastructure/ReverseProxies/Configuration/IConfigProvider.cs
src/Infrastructure/ReverseProxies/Configuration/InMemoryConfigProvider.cs
src/Infrastructure/ReverseProxies/YarpReverseProxy.cs

abstracts away the implementation details of the InMemoryConfigProvider from YarpReverseProxy so that other config providers can be used.
Required for #368

extract to IConfigProvider

---

src/Application/Channels/Commands/UpdateChannelCommandValidator.cs
tests/Hippo.FunctionalTests/Application/Channels/Commands/UpdateChannelTests.cs

fixes a loophole where an update can allow the user to enter an invalid channel name.

apply BeUniqueNameForApp validator to UpdateChannelCommand

---

src/Application/Certificates/Commands/CreateCertificateCommand.cs
src/Application/Certificates/Commands/UpdateCertificateCommand.cs
src/Application/Channels/Commands/CreateChannelCommand.cs
src/Application/Channels/Commands/UpdateChannelCommand.cs
src/Application/Channels/EventHandlers/CertificateBindEventHandler.cs
src/Application/Revisions/EventHandlers/RevisionCreatedEventHandler.cs
src/Application/Revisions/EventHandlers/RevisionDeletedEventHandler.cs
src/Core/Entities/Channel.cs
src/Core/Events/ActiveRevisionChangedEvent.cs
src/Core/Events/CertificateBindEvent.cs
src/Core/Events/CertificateUnbindEvent.cs
src/Core/_Imports.cs
src/Web/Controllers/ChannelController.cs
tests/Core.UnitTests/Events/EventTests.cs
tests/Hippo.FunctionalTests/Application/Channels/Commands/CreateChannelTests.cs
tests/Hippo.FunctionalTests/Application/Channels/Commands/UpdateChannelTests.cs

The API should be accepting a Certificate ID rather than a concrete object type.
I also refactored some of the DomainEvents such that the code remains a little more DRY.
This was discovered while integrating hippo-openapi into hippo-cli via https://github.com/deislabs/hippo-cli/pull/99. This is a breaking change to the API and will require the clients to be regenerated.

fix CreateChannelCommand

---

src/Web/Controllers/AppController.cs
src/Web/Controllers/ChannelController.cs
src/Web/Controllers/EnvironmentVariableController.cs

HTML forms do not allow for DELETE methods.

fix(ui): delete confirmations using correct method

---

src/Application/Apps/Commands/CreateAppCommandValidator.cs
src/Application/Apps/Commands/UpdateAppCommandValidator.cs
tests/Hippo.FunctionalTests/Application/Apps/Commands/CreateAppTests.cs

The previous regular expression would not allow hyphens in the storage
ID.

fix storage ID regex

---

src/Web/Program.cs

The rust client sends "0" as the value, as generated by the openapi project. We need to tell .NET that it should accept string values for enum conversions.
closes https://github.com/deislabs/hippo-cli/issues/120

handle enum string conversions

---

src/Web/Program.cs

dead code; no longer required after #421 was implemented.

remove views

---

src/Application/Revisions/EventHandlers/RevisionCreatedEventHandler.cs

When the channel's `ActiveRevision` changes, we need to fire off a
ModifiedEvent<Channel> so that hippo can properly update the job
scheduler.

Fix: fire ModifiedEvent<Channel>

---

src/Web/appsettings.Development.json
src/Web/appsettings.json

Hippo would not report much other than fail messages. In production,
we'd like to log everything other than warnings and error messages.

improve production logging

---

.devcontainer/devcontainer.json
.github/workflows/build-devcontainer.yml

This makes hippo-dev match `ghcr.io/deislabs/hippo` as well as the current hippo version. That way the developer knows they have the right dev container version.

Downgrade hippo-dev to match hippo version

---

src/Application/Common/Config/HippoConfig.cs
src/Web/appsettings.Development.json

.local is reserved on MacOS for mDNS
https://blog.scottlowe.org/2006/01/04/mac-os-x-and-local-domains/

change hippofactory.local to hippo.localdomain

---

src/Application/Apps/Commands/CreateAppCommand.cs
src/Application/Apps/Commands/DeleteAppCommand.cs
src/Application/Apps/Commands/UpdateAppCommand.cs
src/Application/Certificates/Commands/CreateCertificateCommand.cs
src/Application/Certificates/Commands/DeleteCertificateCommand.cs
src/Application/Certificates/Commands/UpdateCertificateCommand.cs
src/Application/Channels/Commands/CreateChannelCommand.cs
src/Application/Channels/Commands/DeleteChannelCommand.cs
src/Application/Channels/Commands/UpdateChannelCommand.cs
src/Application/EnvironmentVariables/Commands/CreateEnvironmentVariableCommand.cs
src/Application/EnvironmentVariables/Commands/DeleteEnvironmentVariableCommand.cs
src/Application/EnvironmentVariables/Commands/UpdateEnvironmentVariableCommand.cs
src/Application/Revisions/Commands/CreateRevisionCommand.cs
src/Application/Revisions/Commands/DeleteRevisionCommand.cs
src/Application/Revisions/Commands/RegisterRevisionCommand.cs
src/Infrastructure/Data/ApplicationDbContext.cs

This ensures when entities are modified, created, or deleted, the generic Created/Modified/Deleted event is emitted.
Closes #613

emit events at the infrastructure layer

---

src/Infrastructure/Jobs/NomadJob.cs

The nomad exec driver is only available on Linux.

feat(nomad): Make nomad driver configurable

---

src/Web/ClientApp/src/app/components/account/register/register.component.html
src/Web/ClientApp/src/app/components/account/register/register.component.ts

Fixes an issue where the password mismatch and minimum length requirement errors would not be displayed.
https://github.com/deislabs/hippo/pull/707 presents server-side errors, but we're performing some client-side validation as well.
closes #673.

display password mismatch and minlength errors

---

src/Web/ClientApp/package.json
src/Web/Web.csproj

wwwroot wasn't being cleaned up properly, nor was the correct `npm run` script.

fix `dotnet publish`

---

.github/workflows/release.yml

the current release workflow will not cut a release if I use the Semantic Versioning build number or pre-release system. Instead it relies on a `-preview` tag, when normally we follow the release candidate (`-rc.1`) pattern for versioning.

cut release on any tag

---

src/Web/Api/ApiControllerBase.cs
src/Web/Program.cs
src/Web/Web.csproj

Clients can now understand what API versions Hippo is serving at any point. Clients can point to specific API versions by adding the `Api-Version` header to their requests. As of right now the first API version is 0.1, which is assumed by default.
A client implementation is still required. Clients should read the `api-supported-versions` header to determine compatibility with the server.
See https://www.telerik.com/blogs/your-guide-rest-api-versioning-aspnet-core for more details.

Introduce API versioning

---

src/Web/appsettings.Development.json

hippo.localdomain is the default platform domain.

remove duplicate domain

---

src/Web/Web.csproj

This enables `dotnet run`/`dotnet watch` to re-run `npm run publish`. Right now it only runs if `dotnet publish` is invoked.

Run `npm run publish` on build

---

src/Application/Apps/Commands/CreateAppCommandValidator.cs
src/Application/Common/Interfaces/BindleService/RevisionComponent.cs

+ This change adds Description to RevisionComponent to help
resolve an error being thrown when parsing a spin toml parcel
from a bindle.
+ This resolves the 500 I was seeing when trying to create an app
+ Also updated the storage id not found error message
Signed-off-by: Michelle Dhanani <michelle@fermyon.com>

ref(BindleService): add Description to RevisionComponent

---

src/Infrastructure/Services/NomadJobService.cs

I was getting an "invalid socket address" error when deploying spin applications. This change fixes that issue.
https://github.com/fermyon/spin/pull/507#issuecomment-1132928254
Signed-off-by: Michelle Dhanani <michelle@fermyon.com>

ref(nomadjob): update nomad address syntax

---

scripts/nomad-dev.sh

Add a script for starting hippo and nomad for local development.
To access Hippo apps use `*.127.0.0.1.sslip.io:8088`
An example using spin deploy:
```
$ ./script/nomad-dev.sh
$ spin deploy --bindle-server http://localhost:8080/v1 --hippo-server https://localhost:5309
```

tests(nomad): Add a helper script for testing nomad driver

---

src/Application/Accounts/Commands/CreateAccountCommand.cs
src/Application/Apps/Commands/PurgeAppsCommand.cs
src/Application/Certificates/Commands/PurgeCertificatesCommand.cs
src/Application/Channels/Commands/PurgeChannelsCommand.cs
src/Application/Common/Config/HippoConfig.cs
src/Application/Common/Exceptions/ForbiddenAccessException.cs
src/Application/Common/Security/UserPolicy.cs
src/Application/Common/Security/UserRole.cs
src/Application/EnvironmentVariables/Commands/PurgeEnvironmentVariablesCommand.cs
src/Application/Revisions/Commands/PurgeRevisionsCommand.cs
src/Core/Enums/ChannelRevisionSelectionStrategy.cs
src/Core/Enums/RegistrationMode.cs
src/Infrastructure/Data/ApplicationDbContextSeed.cs
src/Infrastructure/DependencyInjection.cs
src/Web/ClientApp/src/app/components/account/register/register.component.ts
src/Web/Filters/ApiExceptionFilterAttribute.cs
src/Web/Program.cs
src/Web/appsettings.json
tests/Core.UnitTests/Enums/RegistrationModeTests.cs
tests/Hippo.FunctionalTests/TestBase.cs

These registration modes restrict who can register new accounts:
- "Open": open registration (the current default behaviour)
- "Closed": closed registration (no users can be registered)
- "AdministratorOnly": only Administrators can create new accounts
In addition, an initial list of administrators can be pre-seeded into the system by setting the "Hippo:Administrators:[(Username, Password)]" fields in appsettings.json.

implement alternative registration modes: "Open", "Closed", and "AdministratorOnly"

---

src/Web/appsettings.json

This was committed by accident while testing the various registration
modes.

fix: remove default registration mode setting to "Closed"

---

src/Web/ClientApp/src/app/components/application/new/new.component.ts

Currently, if you are trying to create an application with a name that contains uppercase letters or underscores, the `CreateChannelCommandValidator` throws an error for the channel Domain property (as the url can't contain capitals or underscores).

Fix / Make sure domain is valid at initial channel creation

---

.github/release-image/Dockerfile

hippo-cli 0.14 does not exist.

revert hippo-cli to 0.12.0

---

.devcontainer/devcontainer.json
.github/release-image/Dockerfile
scripts/README.md
scripts/nomad-dev.sh
src/Application/Common/Config/HippoConfig.cs
src/Web/ClientApp/package.json
src/Web/ClientApp/proxy.conf.js
src/Web/ClientApp/src/app/components/channel/channel.component.html
src/Web/ClientApp/src/app/components/channel/channel.component.ts
src/Web/Program.cs
src/Web/Properties/launchSettings.json

- the default platform domain is now `hippofactory.io`, which contains a wildcard A record pointing to 127.0.0.1
- traefik now listens on both port 80 (http) and port 8081 (dashboard)
- nomad runs as root for `exec` support on linux
- traefik always runs as root so it can listen on port 80
- listens for HTTP requests by default; TLS should be terminated at the load balancer (Traefik)
- the UI now presents the same HTTP/HTTPS protocol for the channel domain

improve nomad-dev script

---

.github/workflows/publish-devcontainer.yml
.github/workflows/publish-nuget.yaml

https://github.com/adamralph/minver#why-is-the-default-version-sometimes-used-in-github-actions-and-travis-ci-when-a-version-tag-exists-in-the-history

set fetch-depth to 0

---

src/Web/ClientApp/src/app/components/application/new/new.component.ts

The path to the app `ListComponent` defined in `app-routing.module.ts` is `/`.
Could not replicate the `/404` redirect after logging in, maybe it was fixed in a more recent Hippo version?

Bugfix 611 /  redirect to app list after creating app

---

src/Web/ClientApp/src/app/components/channel/overview/overview.component.html
src/Web/ClientApp/src/app/components/channel/overview/overview.component.ts

This allows users to click on the HTTP component's route which will open a new page directly to the component.

make channel overview link clickable

---

src/Application/Apps/Queries/AppDto.cs
src/Application/Common/Interfaces/BindleService/RevisionComponent.cs
src/Application/Common/Interfaces/BindleService/RevisionComponentTrigger.cs
src/Application/Common/Interfaces/BindleService/RevisionSpinToml.cs
src/Application/Common/Interfaces/BindleService/RevisionTrigger.cs
src/Application/Revisions/Commands/UpdateRevisionDetailsCommand.cs
src/Application/Revisions/Queries/RevisionComponentDto.cs

This now generates the proper openapi spec for these types:
```
><> curl localhost:5309/swagger/v1/swagger.json -s | jq '.components.schemas.RevisionComponentDto'
{
"required": [
"id",
"name",
"source"
],
"type": "object",
"properties": {
"id": {
"type": "string",
"format": "uuid"
},
"source": {
"type": "string"
},
"name": {
"type": "string"
},
"route": {
"type": "string",
"nullable": true
},
"channel": {
"type": "string",
"nullable": true
},
"type": {
"type": "string",
"nullable": true
}
},
"additionalProperties": false
}
```

nullable types are not required

---

src/Application/Common/Interfaces/BindleService/RevisionComponent.cs

Fields like `files` are used for certain apps like Batholomew.

add other revision component fields

---

src/Infrastructure/Services/NomadJobService.cs

In addition to being more concise, this may avoid issues with IPv6
addresses.
Signed-off-by: Lann Martin <lann.martin@fermyon.com>

fix: Use NOMAD_ADDR_ instead of NOMAD_IP_ + NOMAD_PORT_

---

src/Infrastructure/Services/NomadJobService.cs

This ensures we retrieve a list of jobs that are valid GUIDs. Previously, if there were jobs named like "hippo", "traefik", or "bindle", GetJobs() would return null.

fix: get jobs that are valid GUIDs

---

src/Infrastructure/Services/NomadJobService.cs

Add support for using Nomad's internal service discovery.
This feature depends on nomad v1.3
https://www.nomadproject.io/docs/job-specification/service#provider

feat(nomad): use nomad services

---

src/Core/Models/Page.cs
src/Web/ClientApp/src/app/core/api/v1/model/appItemPage.ts
src/Web/ClientApp/src/app/core/api/v1/model/certificateItemPage.ts
src/Web/ClientApp/src/app/core/api/v1/model/channelItemPage.ts
src/Web/ClientApp/src/app/core/api/v1/model/channelJobStatusItemPage.ts
src/Web/ClientApp/src/app/core/api/v1/model/revisionItemPage.ts
src/Web/ClientApp/src/app/core/api/v1/model/stringPage.ts

The latest version of the OpenAPI spec states that these objects may be optional, forcing the SDKs like Rust and typescript to generate incorrect data types, breaking backwards compatibility.
https://github.com/fermyon/hippo-openapi/blob/db10524c7cbaa8fdf853e0c4264f4589981fb50b/clients/rust/src/models/app_item_page.rs#L17
This forces the OpenAPI generator to mark these fields as required so they are not marked as nullable.

page fields must be required

---

src/Web/ClientApp/src/app/components/account/login/login.component.ts

There is an inconsistency in hippo on the minimum required password length. While the hippo server [login component](https://github.com/deislabs/hippo/blob/main/src/Web/ClientApp/src/app/components/account/login/login.component.ts#L37 ) currently requires a minimum password length of 8, the [CreateAccoundCommandValidator](https://github.com/deislabs/hippo/blob/53757dbe1a3c197f3f429a1d62d2f37e4125f6f3/src/Application/Accounts/Commands/CreateAccountCommandValidator.cs#L25) and [register components](https://github.com/deislabs/hippo/blob/53757dbe1a3c197f3f429a1d62d2f37e4125f6f3/src/Web/ClientApp/src/app/components/account/register/register.component.html#L24) are checking for a min of 6 chars.
This makes them all consistent by having the login form also only require 6. 
fixes #1090 …

bug: ensure login component only requires 6 character password minimum

---

.github/workflows/publish-release.yml

Following up to the [issue](https://github.com/deislabs/hippo/issues/1335) I filed, this changeset adds `linux/arm64` to the release workflow. I'm not sure if this is sufficient to update all the documentation so let me know if there is anything else I need to add.
Edit: Linking the issue #1335

Add `linux-arm64` target runtime to GitHub release workflow 

---

.devcontainer/Dockerfile
.github/release-image/Dockerfile
src/Infrastructure/Services/NomadJobService.cs

* Bump spin to [v0.10.0](https://github.com/fermyon/spin/releases/v0.10.0)
* In v0.10+, the `--follow-all` option for `spin up` is no longer valid; the behavior of that flag is now default (see linked release notes).
See also https://github.com/fermyon/installer/issues/126

chore(*): bump spin and update usage
